config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    passwords: 'user/passwords',
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  devise_scope :admin do
    delete 'admin/logout', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  devise_for :admin, skip: [:session, :passwords, :registrations], controllers: {
    sessions: 'admin/sessions',
  }
  # 管理者アカウントの追加を行う場合、「:registrations」は外す

  # 整理する必要あり

  scope module: 'user' do
    # post 'posts/process_image_analysis', to: 'posts#process_image_analysise'
    resources :users, only: [:show]
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update]
      resource :favorites, only: [:create, :destroy]
      # 単数形：index無し、パスにidが含まれない
      collection do
        get 'tag/:id', to: 'posts#tag', as: :tag
        get 'tags', to: 'posts#tag_index', as: :tags
        get 'inactive', to: 'posts#inactive_index'
        get 'favorites', to: 'favorites#index'
        post :process_image_analysis
        post :process_introduction_analysis
      end
    end
    resources :contacts, only: [:new, :create] do
      collection do
        get 'confirm'
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy, :show] do
      resources :comments, only: [:index, :destroy]
    end
  end

  get 'search' => 'searches#search'
  get '/about' => 'homes#about'
  get '/my_page' => 'user_application#my_page'

  root to: "homes#top"
end

app/controllers/user_application_controller.rb
class UserApplicationController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  before_action :ensure_guest_user, only: [:new]

  layout 'application'

  def my_page
    @my_posts = current_user.posts.page(params[:page])

    if params[:sort] == "created_at_asc"
      @my_posts = @my_posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @my_posts = @my_posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @my_posts = @my_posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @my_posts = @my_posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])

  end

  private
  def ensure_guest_user
    if current_user.guest_user?
      flash[:notice] = "ゲストユーザーは権限がありません。"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/views/user_application/my_page.html.erb
<div class="container">
  <div class="row posts1">
    <%= render 'user/shared/show', user: current_user %>
    <div class="col-md-12 my-3">
      <h2 class="text-center">投稿一覧</h2>
    </div>
    <% if @my_posts.where(is_active: true).any? %>
      <%= render 'user/posts/list', posts: @my_posts, url: my_page_path %>
    <% else %>
      <div class="alert alert-info text-center my-4 mx-auto" role="alert">
        <p>まだ投稿がありません。</p>
      </div>
    <% end %>
  </div>
</div>

app/views/user_application/show.html.erb
<div class="container">
  <div class="row posts1">
    <%= render 'user/shared/show', user: @user %>
    <div class="col-md-12 my-3">
      <h2 class="text-center">投稿一覧</h2>
    </div>
    <% if @posts.where(is_active: true).any? %>
      <%= render 'user/posts/list', posts: @posts, url: user_path(@user) %>
    <% else %>
      <div class="alert alert-info text-center my-4 mx-auto" role="alert">
        <p>まだ投稿がありません。</p>
      </div>
    <% end %>
  </div>
</div>