config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    passwords: 'user/passwords',
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  devise_scope :admin do
    delete 'admin/logout', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  devise_for :admin, skip: [:session, :passwords, :registrations], controllers: {
    sessions: 'admin/sessions',
  }
  # 管理者アカウントの追加を行う場合、「:registrations」は外す

  # 整理する必要あり

  scope module: 'user' do
    # post 'posts/process_image_analysis', to: 'posts#process_image_analysise'
    resources :users, only: [:show]
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update]
      resource :favorites, only: [:create, :destroy]
      # 単数形：index無し、パスにidが含まれない
      collection do
        get 'tag/:id', to: 'posts#tag', as: :tag
        get 'tags', to: 'posts#tag_index', as: :tags
        get 'inactive', to: 'posts#inactive_index'
        get 'favorites', to: 'favorites#index'
        post :process_image_analysis
        post :process_introduction_analysis
      end
    end
    resources :contacts, only: [:new, :create] do
      collection do
        get 'confirm'
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy, :show] do
      resources :comments, only: [:index, :destroy]
    end
  end

  get 'search' => 'searches#search'
  get '/about' => 'homes#about'
  get '/my_page' => 'user_application#my_page'

  root to: "homes#top"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :total_star, :extent_star, :clean_star, :amenity_star, :safety_star, :cost_star, :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminApplicationController
  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_post_path(params[:post_id]), notice: 'コメントを削除しました。'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminApplicationController
  def index
    @user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)

    @comment.total_star = "1"
    @comment.extent_star = "1"
    @comment.clean_star = "1"
    @comment.amenity_star = "1"
    @comment.safety_star = "1"
    @comment.cost_star = "1"
    # 仮データ

    if @comment.save
      redirect_to post_path(@post), notice: 'コメントを投稿しました。'
    else
      Rails.logger.error(@comment.errors.full_messages)
      redirect_back(fallback_location: post_path(@post), alert: 'コメントの投稿に失敗しました。')
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:post_id])

    @comment.total_star = "1"
    @comment.extent_star = "1"
    @comment.clean_star = "1"
    @comment.amenity_star = "1"
    @comment.safety_star = "1"
    @comment.cost_star = "1"
    # 仮データ

  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = "コメントが更新されました。"
      redirect_to post_path(@post)
    else
      flash[:alert] = "コメントの更新に失敗しました。"
      render :edit
    end
  end

  private
  def comment_params
    # params.require(:comment).permit(:comment, :total_star, :extent_star, :clean_star, :amenity_star, :safety_star, :cost_star, :user_id, :post_id)
    params.require(:comment).permit(:comment, :user_id, :post_id, :total_star, :extent_star, :clean_star, :amenity_star, :safety_star, :cost_star)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserApplicationController
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :ensure_guest_user

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post), notice: 'コメントを投稿しました。'
    else
      flash[:error] = @comment.errors.full_messages.join("\n")
      redirect_back(fallback_location: post_path(@post))
      # render "user/posts/show"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comments = @post.comments.page(params[:page])
    Comment.find(params[:id]).destroy
    flash[:notice] = 'コメントを削除しました'
    # redirect_to post_path(params[:post_id]), notice: 'コメントを削除しました。'
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = "コメントが更新されました。"
      redirect_to post_path(@post)
    else
      flash[:error] = @comment.errors.full_messages
      render :edit
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :post_id, :total_star, :extent_star, :clean_star, :amenity_star, :safety_star, :cost_star)
  end

  def authorize_user
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    unless comment.user_id == current_user.id
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      render :new
    end
  end

  def done
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < UserApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @post_favorite = Favorite.new(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.save
    # redirect_to request.referer
  end

  def destroy
    @post_favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.destroy
    # redirect_to request.referer
  end

  def index
    @posts = Post.joins(:favorites).where(favorites: { user_id: current_user.id }).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts = @posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts = @posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts = @posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: '投稿が成功しました。'
    else
      flash[:error] = @post.errors.full_messages.join("\n")
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '投稿が更新されました。'
    else
      flash[:error] = @post.errors.full_messages.join("\n")
      render :edit
    end
  end


  def process_image_analysis
    # Google Cloud Vision API の設定
    require "google/cloud/vision"
    image_annotator = Google::Cloud::Vision.image_annotator do |config|
      config.credentials = ENV["GOOGLE_API_KEY"]
    end

    # APIに画像を解析リクエスト送信
    results = []
    images = []
    params[:post][:images].each do |image|
      pp image.tempfile.path
      images.push(image.tempfile.path)
    end
    images.each do |image|
      response = image_annotator.label_detection(image: image) # 例としてlabel_detectionを使用
      results += response.responses.flat_map(&:label_annotations).map(&:description)
    end
    pp results
    # 解析結果からタグIDを取得する処理（API連携の部分は省略）
    tag_ids = fetch_tags_from_results(results)

    render json: { tag_ids: tag_ids }
  rescue Google::Cloud::Error => e
    Rails.logger.error("画像認識エラー: #{e.message}")
    render json: { error: "Image analysis failed." }, status: :unprocessable_entity
  end

  def process_introduction_analysis
    tag_ids = []
    introduction_text = params[:post][:introduction]

    # タグのnameがintroduction_textに含まれるかを部分一致で検索
    Tag.all.each do |tag|
      tag_name = tag.name

      # タグ名を意味的に分割して、紹介文に一致するか確認
      tag_name.scan(/([一-龯々]+|[ァ-ヴー]+|[A-Za-z0-9]+|[、。])/).each do |match|
        pp match
        if introduction_text.include?(match[0])
          tag_ids << tag.id
          break  # 一度一致すれば、そのタグを追加して次のタグへ
        end
      end
    end

    tag_ids.uniq!
    render json: { tag_ids: tag_ids }
  end

  def fetch_tags_from_results(results)
    tag_ids = []
    results.each do |label|
      matching_tags = Tag.where("english_word LIKE ?", "%#{label}%")
      tag_ids.concat(matching_tags.pluck(:id)) if matching_tags.any?
    end
    tag_ids.uniq
    # 重複を排除
  end

  def index
    @posts = Post.where(is_active: true).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts = @posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts = @posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts = @posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    elsif params[:sort] == "star_at_desc"
      # @posts = @posts.order(average_total_star: :desc)
      # @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments_total_star.id) DESC')
      @posts = @posts.left_joins(:comments).group('posts.id').reorder(Arel.sql('COALESCE(AVG(comments.total_star), 0) DESC'))

    end
  end

  def tag
    @tag = Tag.find(params[:id])
    @posts_only_tag = @tag.posts.where(is_active: true).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts_only_tag = @posts_only_tag.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts_only_tag = @posts_only_tag.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts_only_tag = @posts_only_tag.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts_only_tag = @posts_only_tag.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end

  end

  def show
    @post_user = @post.user
    @comment = Comment.new
    @comments = @post.comments.page(params[:page])
    if (@post.is_active == false) && (@post.user != current_user)
      respond_to do |format|
        format.html { redirect_to posts_path, notice: 'このページにはアクセスできません' }
      end
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '投稿が削除されました。'
  end

  def tag_index
    @tags = Tag.all
  end

  def inactive_index
    @inactive_posts = Post.where(is_active: false).page(params[:page])

    if params[:sort] == "created_at_asc"
      @inactive_posts = @inactive_posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @inactive_posts = @inactive_posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @inactive_posts = @inactive_posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @inactive_posts = @inactive_posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end

  end

  private
  def post_params
    params.require(:post).permit(:title, :address, :hp, :introduction, :user_id, :is_active, tag_ids: [], images: [])
  end

  def authorize_user
    unless @post.user_id == current_user.id
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :ensure_guest_user, only: [:edit]

  # update/destroy不要かも

  def destroy
    super do
      redirect_to new_user_registration_path and return
    end
  end

  def after_update_path_for(resource)
    my_page_path
  end

  # def edit
  #   @user = current_user
  #   super()
  # end




  def after_sign_in_path_for(resource)
    my_page_path
  end

  private
  def authorize_user!
    user_id = params[:format] || current_user.id
    @user = User.find(user_id)
    unless @user == current_user
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end

  def ensure_guest_user
    if current_user.guest_user?
      flash[:notice] = "ゲストユーザーは権限がありません。"
      redirect_back(fallback_location: root_path)
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/views/user/comments/_average_star.html.erb
<% if average_total_star == 0 %>
  <span>まだ評価がありません</span>
<% else %>
  <span id="star_average_<%= post.id %>"></span>
  <script>
      var elem = document.querySelector('#star_average_<%= post.id %>');
      if (elem != null) {
      elem.innerHTML = ""
      var opt = {
        score: "<%= average_total_star.present? ? average_total_star : 0 %>",
        readOnly: true,
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
      };
      raty(elem, opt);
      }
  </script>
<% end %>

app/views/user/comments/_index.html.erb
<!--each使えるか検証→OK-->
<% ratings = [
  { label: "総合評価　　　　　　：", score_type: :total_star },
  { label: "ドッグランの広さ　　：", score_type: :extent_star },
  { label: "清潔さ　　　　　　　：", score_type: :clean_star },
  { label: "アメニティの充実さ　：", score_type: :amenity_star },
  { label: "安全性　　　　　　　：", score_type: :safety_star },
  { label: "コストパフォーマンス：", score_type: :cost_star }
] %>

<div class="row mt-5">
  <div class="col-md-10 mb-4 mx-auto">
    <h2>レビュー一覧</h2>
    <% if comments.any? %>
      <div id="comment_counter">
        <p>レビュー数：<%= comments.count %></p>
      </div>
      <% comments.each do |comment| %>
        <div class="card shadow-sm mt-4">
          <div class="card-body">
            <div class="card-title">
              <p>投稿者：<%= link_to comment.user.name, user_path(post.user) %></p>
              <hr>

              <div class="form-group">
                <% ratings.each do |rating| %>
                  <div class="d-flex align-items-center mb-2">
                    <p class="my-auto"><%= rating[:label] %></p>
                    <div id="star_<%= rating[:score_type] %>_<%= comment.id %>"></div>
                  </div>
                  <script>
                      var elem = document.querySelector('#star_<%= rating[:score_type] %>_<%= comment.id %>');
                      if (elem != null) {
                        elem.innerHTML = ""
                        var opt = {
                          score: "<%= comment[rating[:score_type]].present? ? comment[rating[:score_type]] : 0 %>",
                          readOnly: true,
                          starOn: "<%= asset_path('star-on.png') %>",
                          starOff: "<%= asset_path('star-off.png') %>",
                        };
                        raty(elem, opt);
                      }
                  </script>
                <% end %>
              </div>
              <hr>


              <p class="card-text"><%= comment.comment %></p>
              <small class="text-muted"> - 投稿日：<%= comment.created_at.strftime("%Y/%m/%d") %></small>
            </div>
          </div>
          <div class="pb-3">
            <% if current_admin %>
              <%= link_to '削除', admin_post_comment_path(post, comment), data: { confirm: '本当に削除しますか？' }, method: :delete, class: "btn btn-danger mx-4" %>
            <% elsif comment.user_id == current_user.id %>
              <%= link_to '編集', edit_post_comment_path(post, comment), class: "btn btn-success mx-4" %>
              <%= link_to '削除', [post, comment], data: { confirm: '本当に削除しますか？' }, method: :delete, class: "btn btn-danger mx-4", remote: true %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>まだレビューがありません。</p>
    <% end %>
  </div>
</div>
<div class="row my-3 justify-content-center">
  <div class="col-auto">
    <div id="flash-message"></div>
    <%= paginate comments, outer_window: 3 %>
  </div>
</div>
<hr>

app/views/user/comments/_new.html.erb
<% ratings = [
  { label: "総合評価　　　　　　：", score_type: :total_star },
  { label: "ドッグランの広さ　　：", score_type: :extent_star },
  { label: "清潔さ　　　　　　　：", score_type: :clean_star },
  { label: "アメニティの充実さ　：", score_type: :amenity_star },
  { label: "安全性　　　　　　　：", score_type: :safety_star },
  { label: "コストパフォーマンス：", score_type: :cost_star }
] %>

<div class="row my-5">
  <div class="col-md-10 mb-4 mx-auto">
    <h2 class="pb-4">レビュー投稿</h2>
    <% if post.comments.exists?(user_id: current_user.id) %>
      <p>既に投稿済みです。</p>
    <% else %>


      <div class="card shadow-sm p-4">
        <% if flash[:error] %>
          <div class="alert alert-danger">
            <p><%= simple_format(flash[:error]) %></p>
          </div>
        <% end %>

        <%= form_with model: [post, comment] do |f| %>
          <div class="form-group" id="star">
            <% ratings.each do |rating| %>
              <div class="d-flex align-items-center mb-2">
                <p class="mt-3"><%= rating[:label] %></p>
                <%= f.hidden_field rating[:score_type], id: "comment_review_#{rating[:score_type]}", class: 'form-control' %>
                <div id="comment_<%= rating[:score_type] %>_raty"></div>
              </div>
            <% end %>
          </div>

          <script>
              let ratings = [
                <% ratings.each do |rating| %>
                  { id: '#comment_<%= rating[:score_type] %>_raty', scoreName: 'comment[<%= rating[:score_type] %>]' },
                <% end %>
              ];

              ratings.forEach(function(rating) {
                let elem = document.querySelector(rating.id);
                if (elem == null) return;

                elem.innerHTML = ""

                let opt = {
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  scoreName: rating.scoreName
                };
                raty(elem, opt);
              });
          </script>

          <hr>
          <div class="form-group pt-2">
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "form-control", style: "width: 100%;", id: "comment_textarea" %>
          </div>

          <%= f.submit "送信", class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/comments/destroy.js.erb
$('#comment_index').html("<%= j(render 'user/comments/index', post: @post, comments: @comments) %>");

$("#flash-message").html("<%= j flash[:notice] %>");


setTimeout(function() {
  $("#flash-message").fadeOut("slow");
}, 3000);

app/views/user/comments/edit.html.erb
<% ratings = [
  { label: "総合評価　　　　　　：", score_type: :total_star },
  { label: "ドッグランの広さ　　：", score_type: :extent_star },
  { label: "清潔さ　　　　　　　：", score_type: :clean_star },
  { label: "アメニティの充実さ　：", score_type: :amenity_star },
  { label: "安全性　　　　　　　：", score_type: :safety_star },
  { label: "コストパフォーマンス：", score_type: :cost_star }
] %>

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 posts1">
      <h1 class="text-center my-3">コメント編集</h1>
      <h5 class="text-secondary">※レビューは編集できません。</h5>

      <div class="form-group">
        <% ratings.each do |rating| %>

        <div class="d-flex align-items-center mb-2">
          <p class="my-auto"><%= rating[:label] %></p>
          <div id="star_<%= rating[:score_type] %>_<%= @comment.id %>"></div>
        </div>
        <script>
            var elem = document.querySelector('#star_<%= rating[:score_type] %>_<%= @comment.id %>');
            if (elem == null) return;
            elem.innerHTML = ""
            var opt = {
              score: "<%= @comment[rating[:score_type]].present? ? @comment[rating[:score_type]] : 0 %>",
              readOnly: true,
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
            };
            raty(elem, opt);
        </script>


        <% end %>
      </div>

      <%= form_with model: [@post, @comment], local: true do |comment| %>
        <%= comment.text_area :comment, rows: '5', class: "form-control", style: "width: 100%;", required: true %>
        <!--required：空欄で保存できない設定-->
      <div class="form-group my-5">
        <%= comment.hidden_field :post_id, value: @post.id %>
        <%= comment.submit '保存', class: 'btn btn-primary btn-block mb-5' %>
        <%= link_to '削除', post_comment_path(@comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-block" %>
      </div>
    <% end %>

    </div>
  </div>
</div>