config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    passwords: 'user/passwords',
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  devise_scope :admin do
    delete 'admin/logout', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  devise_for :admin, skip: [:session, :passwords, :registrations], controllers: {
    sessions: 'admin/sessions',
  }
  # 管理者アカウントの追加を行う場合、「:registrations」は外す

  # 整理する必要あり

  scope module: 'user' do
    # post 'posts/process_image_analysis', to: 'posts#process_image_analysise'
    resources :users, only: [:show]
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update]
      resource :favorites, only: [:create, :destroy]
      # 単数形：index無し、パスにidが含まれない
      collection do
        get 'tag/:id', to: 'posts#tag', as: :tag
        get 'tags', to: 'posts#tag_index', as: :tags
        get 'inactive', to: 'posts#inactive_index'
        get 'favorites', to: 'favorites#index'
        post :process_image_analysis
        post :process_introduction_analysis
      end
    end
    resources :contacts, only: [:new, :create] do
      collection do
        get 'confirm'
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy, :show] do
      resources :comments, only: [:index, :destroy]
    end
  end

  get 'search' => 'searches#search'
  get '/about' => 'homes#about'
  get '/my_page' => 'user_application#my_page'

  root to: "homes#top"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user_or_admin!

  def search
    @word = params[:word]
    @posts = Post.where("is_active = :active AND (title LIKE :word OR introduction LIKE :word OR address LIKE :word OR hp LIKE :word)", active: true, word: "%#{@word}%").page(params[:page])
    @users = User.where("name LIKE ?", "%#{@word}%")
    @tags = Tag.where("name LIKE ?", "%#{@word}%")

    if params[:sort] == "created_at_asc"
      @posts = @posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts = @posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts = @posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    elsif params[:sort] == "star_at_desc"
      # @posts = @posts.order(average_total_star: :desc)
      @posts = @posts.left_joins(:comments).group('posts.id').reorder(Arel.sql('COALESCE(AVG(comments.total_star), 0) DESC'))
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
<div>
  <%= form_with url: search_path, local: true, method: :get do |search| %>
    <%= search.text_field :word, placeholder:' キーワード検索', style: 'font-size: 18px;', class: "rounded border-0" %>
    <%= search.submit "検索", class: "btn btn-outline-light btn-sm mb-1" %>
  <% end %>
</div>

app/views/searches/search.html.erb
<div class="container my-4 posts1">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center mb-4">検索結果</h2>
      <div style="border-bottom: 1rem solid #ffebcd; margin: 20px 0;"></div>

      <div class="my-5">
        <h3 class="mb-3">投稿検索一覧</h3>
        <% if @posts.any? %>

          <div class='w-100 mb-4 text-center'>
            <%= form_with url: search_path, method: :get do |sort| %>
              <%= sort.select :sort, options_for_select([['投稿順(古)', 'created_at_asc'], ['投稿順(新)', 'created_at_desc'], ['ブックマーク順', 'favorited_desc'], ['コメント件数順', 'comments_desc'],['総合評価順(高)', 'star_at_desc']], params[:sort]) %>
              <%= sort.hidden_field :word, value: @word %>
              <%= sort.submit '並び替え', class: "btn btn-secondary btn-sm" %>
            <% end %>
          </div>
          <table class="table table-striped">
            <thead>
              <tr>
                <th></th>
                <th class="no1">ドッグラン名</th>
                <th class="no1">紹介文</th>
                <th class="no1 text-center">コメント数</th>
                <th class="no1 text-center">ブックマーク数</th>
                <th class="no1 text-center">平均総合評価</th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td class="text-center">
                    <div class="swiper index-swiper" id="swiper-<%= post.id %>">

                      <div class="swiper-wrapper"style="width: 300px; height: 300px;">
                        <% post.images.each do |image| %>
                          <div class="swiper-slide">
                            <%= image_tag image, size: "300x300", class: 'img-thumbnail' %>
                          </div>
                        <% end %>
                      </div>
                      <div class="swiper-pagination"></div>
                      <div class="swiper-button-prev"></div>
                      <div class="swiper-button-next"></div>
                    </div>
                  </td>

                  <script>
                    swiper = new Swiper("#swiper-<%= post.id %>", {
                      loop: true, // ループ
                      speed: 3000, // 少しゆっくり(デフォルトは300)
                      autoplay: { // 自動再生
                        delay: 1000, // 1秒後に次のスライド
                        disableOnInteraction: false, // 矢印をクリックしても自動再生を止めない
                      },
                      // ページネーション
                      pagination: {
                        el: ".swiper-pagination",
                        clickable: true,
                      },
                      // 前後の矢印
                      navigation: {
                        nextEl: ".swiper-button-next",
                        prevEl: ".swiper-button-prev",
                      },
                    });
                  </script>

                  <td data-label="ドッグラン名：" class="pl-3 align-middle"><%= link_to post.title, post_path(post), class: 'text-primary' %></td>
                  <td class="pl-2 align-middle"><span class="text-muted"> - <%= post.introduction %></span></td>
                  <td data-label="コメント数　　：", class="text-center align-middle"><%= post.comments.count %></td>
                  <td data-label="ブックマーク数：", class="text-center align-middle"><%= post.favorites.count %></td>
                  <td data-label="平均総合評価：", class="text-center align-middle">
                    <% if post.comments.any? %>
                      <%= post.comments.average(:total_star).to_f.round(1) %>
                    <% else %>
                    -
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row my-3 mx-auto">
            <%= paginate @posts, outer_window: 3 %>
          </div>
        <% else %>
          <p class="text-muted">投稿が見つかりませんでした。</p>
        <% end %>
      </div>
      <div class="my-5">
        <div style="border-bottom: 1rem solid #ffebcd; margin: 20px 0;"></div>
        <h3>ユーザー検索一覧</h3>
        <% if @users.any? %>
          <table class="table table-striped text-center">
            <thead>
              <tr>
                <th>ユーザー名</th>
                <th>投稿数</th>
                <th>コメント数</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td class="pl-2" data-label="ユーザー名："><%= user.name %></td>
                  <td class="pl-2" data-label="投稿数　　："><%= user.posts.count %></td>
                  <td class="pl-2" data-label="コメント数："><%= user.comments.count %></td>
                  <td>
                  <% if user_signed_in? %>
                    <%= link_to '詳細', user_path(user), class: 'btn btn-primary' %>
                  <% else %>
                    <%= link_to '詳細', admin_user_path(user), class: 'btn btn-primary' %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p class="text-muted">ユーザーが見つかりませんでした。</p>
        <% end %>
      </div>

      <div class="my-3">
        <div style="border-bottom: 1rem solid #ffebcd; margin: 20px 0;"></div>
        <h3>タグ検索一覧</h3>
        <% if @tags.any? %>
          <% @tags.each do |tag| %>
            <div class="card h-100">
              <div class="card-body d-flex flex-column justify-content-between">
                <h5 class="card-title text-truncate"><%= tag.name %></h5>
                <div class="mt-auto">
                  <% if current_admin %>
                    <%= link_to '編集', edit_admin_tag_path(tag), class: "btn btn-success btn-sm" %>
                    <%= link_to '削除', admin_tag_path(tag), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %>
                  <% else %>
                    <%= link_to '投稿一覧を見る', tag_posts_path(tag.id), class: "btn btn-primary btn-sm" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="text-muted">タグが見つかりませんでした。</p>
        <% end %>
      </div>

    </div>
  </div>
</div>