config/routes.rb
Rails.application.routes.draw do
  namespace :user do
    get 'contacts/new'
    get 'contacts/confirm'
    get 'contacts/done'
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    passwords: 'user/passwords',
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  devise_scope :admin do
    delete 'admin/logout', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  devise_for :admin, skip: [:session, :passwords, :registrations], controllers: {
    sessions: 'admin/sessions',
  }
  # 管理者アカウントの追加を行う場合、「:registrations」は外す

  # 整理する必要あり

  scope module: 'user' do
    # post 'posts/process_image_analysis', to: 'posts#process_image_analysise'
    resources :users, only: [:show]
    resources :posts do
      resources :comments, only: [:create, :destroy, :edit, :update]
      resource :favorites, only: [:create, :destroy]
      # 単数形：index無し、パスにidが含まれない
      collection do
        get 'tag/:id', to: 'posts#tag', as: :tag
        get 'tags', to: 'posts#tag_index', as: :tags
        get 'inactive', to: 'posts#inactive_index'
        get 'favorites', to: 'favorites#index'
        post :process_image_analysis
        post :process_introduction_analysis
      end
    end
    resources :contacts, only: [:new, :create] do
      collection do
        get 'confirm'
        post 'confirm'
        post 'back'
        get 'done'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy, :show]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy, :show] do
      resources :comments, only: [:index, :destroy]
    end
  end

  get 'search' => 'searches#search'
  get '/about' => 'homes#about'
  get '/my_page' => 'user_application#my_page'

  root to: "homes#top"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :images, :title, :address, :hp, :introduction, presence: true
  validates :address, :hp, uniqueness: true
  validate :image_length

  has_many_attached :images
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    unless user.nil?
      favorites.exists?(user_id: user.id)
    end
  end
  # userがいいねしているか

  def average_total_star
    average = comments.average(:total_star)
    if average.present?
      (average * 2).round / 2.0
    else
      0
    end
  end

  private
  def image_length
    if images.count > 5
      # images.length > 5 qiitaでは「length」を使用
      errors.add(:images, "は5枚以内にしてください。")
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminApplicationController
  before_action :set_post, only: [:show, :destroy]

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page])
  end

  def index
    @posts = Post.all.page(params[:page])
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '投稿が削除されました。'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminApplicationController
  def index
    @user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < UserApplicationController
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :new]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: '投稿が成功しました。'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '投稿が更新されました。'
    else
      render :edit
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post_user = @post.user
    @comment = Comment.new
    @post = Post.find(params[:id])
  end

  def edit
  end

  def destroy
    @post.delete
    redirect_to my_page_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :address, :hp, :introduction, :user_id, :image)
  end

  def authorize_user
    unless @post.user_id == current_user.id
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < UserApplicationController
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :ensure_guest_user

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post), notice: 'コメントを投稿しました。'
    else
      flash[:error] = @comment.errors.full_messages.join("\n")
      redirect_back(fallback_location: post_path(@post))
      # render "user/posts/show"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comments = @post.comments.page(params[:page])
    Comment.find(params[:id]).destroy
    flash[:notice] = 'コメントを削除しました'
    # redirect_to post_path(params[:post_id]), notice: 'コメントを削除しました。'
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = "コメントが更新されました。"
      redirect_to post_path(@post)
    else
      flash[:error] = @comment.errors.full_messages
      render :edit
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :post_id, :total_star, :extent_star, :clean_star, :amenity_star, :safety_star, :cost_star)
  end

  def authorize_user
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    unless comment.user_id == current_user.id
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      render :new
    end
  end

  def done
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < UserApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @post_favorite = Favorite.new(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.save
    # redirect_to request.referer
  end

  def destroy
    @post_favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    @post_favorite.destroy
    # redirect_to request.referer
  end

  def index
    @posts = Post.joins(:favorites).where(favorites: { user_id: current_user.id }).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts = @posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts = @posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts = @posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: '投稿が成功しました。'
    else
      flash[:error] = @post.errors.full_messages.join("\n")
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '投稿が更新されました。'
    else
      flash[:error] = @post.errors.full_messages.join("\n")
      render :edit
    end
  end


  def process_image_analysis
    # Google Cloud Vision API の設定
    require "google/cloud/vision"
    image_annotator = Google::Cloud::Vision.image_annotator do |config|
      config.credentials = ENV["GOOGLE_API_KEY"]
    end

    # APIに画像を解析リクエスト送信
    results = []
    images = []
    params[:post][:images].each do |image|
      pp image.tempfile.path
      images.push(image.tempfile.path)
    end
    images.each do |image|
      response = image_annotator.label_detection(image: image) # 例としてlabel_detectionを使用
      results += response.responses.flat_map(&:label_annotations).map(&:description)
    end
    pp results
    # 解析結果からタグIDを取得する処理（API連携の部分は省略）
    tag_ids = fetch_tags_from_results(results)

    render json: { tag_ids: tag_ids }
  rescue Google::Cloud::Error => e
    Rails.logger.error("画像認識エラー: #{e.message}")
    render json: { error: "Image analysis failed." }, status: :unprocessable_entity
  end

  def process_introduction_analysis
    tag_ids = []
    introduction_text = params[:post][:introduction]

    # タグのnameがintroduction_textに含まれるかを部分一致で検索
    Tag.all.each do |tag|
      tag_name = tag.name

      # タグ名を意味的に分割して、紹介文に一致するか確認
      tag_name.scan(/([一-龯々]+|[ァ-ヴー]+|[A-Za-z0-9]+|[、。])/).each do |match|
        pp match
        if introduction_text.include?(match[0])
          tag_ids << tag.id
          break  # 一度一致すれば、そのタグを追加して次のタグへ
        end
      end
    end

    tag_ids.uniq!
    render json: { tag_ids: tag_ids }
  end

  def fetch_tags_from_results(results)
    tag_ids = []
    results.each do |label|
      matching_tags = Tag.where("english_word LIKE ?", "%#{label}%")
      tag_ids.concat(matching_tags.pluck(:id)) if matching_tags.any?
    end
    tag_ids.uniq
    # 重複を排除
  end

  def index
    @posts = Post.where(is_active: true).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts = @posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts = @posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts = @posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    elsif params[:sort] == "star_at_desc"
      # @posts = @posts.order(average_total_star: :desc)
      # @posts = @posts.left_joins(:comments).group('posts.id').order('COUNT(comments_total_star.id) DESC')
      @posts = @posts.left_joins(:comments).group('posts.id').reorder(Arel.sql('COALESCE(AVG(comments.total_star), 0) DESC'))

    end
  end

  def tag
    @tag = Tag.find(params[:id])
    @posts_only_tag = @tag.posts.where(is_active: true).page(params[:page])

    if params[:sort] == "created_at_asc"
      @posts_only_tag = @posts_only_tag.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @posts_only_tag = @posts_only_tag.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @posts_only_tag = @posts_only_tag.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @posts_only_tag = @posts_only_tag.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end

  end

  def show
    @post_user = @post.user
    @comment = Comment.new
    @comments = @post.comments.page(params[:page])
    if (@post.is_active == false) && (@post.user != current_user)
      respond_to do |format|
        format.html { redirect_to posts_path, notice: 'このページにはアクセスできません' }
      end
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '投稿が削除されました。'
  end

  def tag_index
    @tags = Tag.all
  end

  def inactive_index
    @inactive_posts = Post.where(is_active: false).page(params[:page])

    if params[:sort] == "created_at_asc"
      @inactive_posts = @inactive_posts.order(created_at: :asc)
    elsif params[:sort] == "created_at_desc"
      @inactive_posts = @inactive_posts.order(created_at: :desc)
    elsif params[:sort] == "favorited_desc"
      @inactive_posts = @inactive_posts.left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    elsif params[:sort] == "comments_desc"
      @inactive_posts = @inactive_posts.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    end

  end

  private
  def post_params
    params.require(:post).permit(:title, :address, :hp, :introduction, :user_id, :is_active, tag_ids: [], images: [])
  end

  def authorize_user
    unless @post.user_id == current_user.id
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :ensure_guest_user, only: [:edit]

  # update/destroy不要かも

  def destroy
    super do
      redirect_to new_user_registration_path and return
    end
  end

  def after_update_path_for(resource)
    my_page_path
  end

  # def edit
  #   @user = current_user
  #   super()
  # end




  def after_sign_in_path_for(resource)
    my_page_path
  end

  private
  def authorize_user!
    user_id = params[:format] || current_user.id
    @user = User.find(user_id)
    unless @user == current_user
      redirect_back(fallback_location: posts_path, alert: "権限がないため、この操作を実行できません。")
    end
  end

  def ensure_guest_user
    if current_user.guest_user?
      flash[:notice] = "ゲストユーザーは権限がありません。"
      redirect_back(fallback_location: root_path)
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/views/user/posts/_list.html.erb
<div class="row col-md-12">
  <div class="col-md-3">
    <h3 class="ml-2">目次</h3>


    <div class="card p-3 shadow-lg rounded-3">
      <% posts.each_with_index do |post, index| %>
          <h5 class="card-title">
            <%= link_to post.title, "#post-#{post.id}", class: "text-dark" %>
          </h5>
        <% unless index == posts.length - 1 %>
          <hr><!-- 最後の投稿には区切り線を表示しない -->
        <% end %>
      <% end %>
    </div>


  </div>
  <div class="col-md-9">
    <div class='w-100 my-2 text-center'>
      <%= form_with url: url, method: :get do |sort| %>
        <%= sort.select :sort, options_for_select([['投稿順(古)', 'created_at_asc'], ['投稿順(新)', 'created_at_desc'], ['ブックマーク順', 'favorited_desc'], ['コメント件数順', 'comments_desc'],['総合評価順(高)', 'star_at_desc']], params[:sort]) %>
        <%= sort.submit '並び替え', class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
    <div><!-- card start -->
    <% posts.each do |post| %>
      <div class="card shadow mx-2 p-1 mb-4 index-card d-flex justify-content-center" id="post-<%= post.id %>">

        <div class="swiper index-swiper pt-3" id="swiper-<%= post.id %>">

          <div class="swiper-wrapper">
            <% post.images.each do |image| %>
              <div class="swiper-slide">
                <%= image_tag image, class: "square-image card-img-top" %>
              </div>
            <% end %>
          </div>
          <div class="swiper-pagination"></div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>

        <script>
              swiper = new Swiper("#swiper-<%= post.id %>", {
              loop: true, // ループ
              speed: 3000, // 少しゆっくり(デフォルトは300)
              autoplay: { // 自動再生
                delay: 1000, // 1秒後に次のスライド
                disableOnInteraction: false, // 矢印をクリックしても自動再生を止めない
              },
              // ページネーション
              pagination: {
                el: ".swiper-pagination",
                clickable: true,
              },
              // 前後の矢印
              navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
              },
            });
        </script>

        <div class="card-body">
          <p>
            <% post.tags.each do |tag| %>
              <button type="button" class="btn btn-secondary btn-sm mb-1" disabled>
                <span><%= link_to tag.name, tag_posts_path(tag.id), class: "text-white" %></span>
              </button>
            <% end %>
          </p>

          <h3 class="card-title"><%= post.title %></h3>
          <p class="card-text"><%= post.introduction %></p>
          <hr>
          <p><%= post.address %></p>
          <hr>
          <p class="card-text">コメント数　　：<%= post.comments.count %></p>
          <hr>
          <p>
             <strong>ブックマーク数：</strong>
            <span id="favorite_btn_<%= post.id %>"><%= render 'user/favorites/btn', post: post %></span>
          </p>
          <hr>
          <p>平均総合評価　：<%= render 'user/comments/average_star', average_total_star: post.average_total_star, post: post %></p>
          <hr>
          <p>投稿日　　　　：<%= post.created_at.strftime("%Y/%m/%d") %></p>

          <p class="mt-2">
            <% if user_signed_in? %>
              <%= link_to "詳しく見る", post_path(post.id, return_to: request.fullpath), class: "btn btn-primary" %>
            <% else %>
              <%= link_to "詳しく見る", admin_post_path(post.id, return_to: request.fullpath), class: "btn btn-primary" %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
    </div><!-- card end -->

  </div>
  <div class="row mx-auto my-3">
    <%= paginate posts, outer_window: 3 %>
  </div>
</div><!-- row end ->

app/views/user/posts/_post_detail.html.erb
<div class="row">
  <h2 class="text-center display-4 my-4 mx-auto title1">ドッグラン詳細</h2>
</div>

<div class="row">
  <div class="col-md-6 d-flex justify-content-center">
    <!--%= image_tag post.images.first, class: "shadow-lg auto-image" %>-->

    <div class="swiper">
      <div class="swiper-wrapper">
        <% post.images.each do |image| %>
          <div class="swiper-slide">
            <%= image_tag image, class: "auto-image" %>
          </div>
        <% end %>
      </div>
      <div class="swiper-pagination"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    </div>

    <script>
      window.onload=function(){
        let swiper = new Swiper(".swiper", {
          loop: true, // ループ
          speed: 3000, // 少しゆっくり(デフォルトは300)
          autoplay: { // 自動再生
            delay: 1000, // 1秒後に次のスライド
            disableOnInteraction: false, // 矢印をクリックしても自動再生を止めない
          },
          // ページネーション
          pagination: {
            el: ".swiper-pagination",
            clickable: true,
          },
          // 前後の矢印
          navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
          },
        });
      };
    </script>

  </div>
  <div class="col-md-6 posts1 mt-10 my-auto">
    <p>
      <% post.tags.each do |tag| %>
        <button type="button" class="btn btn-secondary btn-sm my-2" disabled>
          <span><%= link_to tag.name, tag_posts_path(tag.id), class: "text-white" %></span>
        </button>
      <% end %>
    </p>
    <p><i class="fa-solid fa-marker"></i> <strong>名称：</strong> <%= post.title %></p>
    <hr>
    <p><i class="fas fa-map-marker-alt"></i> <strong>住所：</strong> <%= post.address %></p>
    <small class="text-muted">※実際の情報と異なる可能性があります。</small>
    <hr>
    <p><i class="fas fa-link"></i> <a href="<%= post.hp %>" target="_blank"><%= post.hp %></a></p>
    <small class="text-muted">※実際の情報と異なる可能性があります。</small>
    <hr>
    <p>
      <i class="fas fa-info-circle"></i> <strong>紹介文：</strong>
      <%= sanitize(post.introduction).gsub(/\r\n|\r|\n/, '<br>').html_safe %>
    </p>
    <hr>
    <p><i class="fa-solid fa-user"></i> <strong>投稿者：
    <% if user_signed_in? %>
      <%= link_to post.user.name, user_path(post.user) %>
    <% else %>
      <%= link_to post.user.name, admin_user_path(post.user) %>
    <% end %>
    </strong></p>
    <hr>
    <p>
      <i class="fa-solid fa-thumbs-up"></i> <strong>ブックマーク数：</strong>
      <span id="favorite_btn_<%= post.id %>"><%= render 'user/favorites/btn', post: post %></span>
    </p>
    <hr>
    <p>
      <i class="fa-solid fa-star"></i> <strong>平均総合評価：<%= render 'user/comments/average_star', average_total_star: post.average_total_star, post: post %></strong>
    </p>
    <hr>
    <p><i class="fa-solid fa-calendar"></i> 投稿日：<%= post.created_at.strftime("%Y/%m/%d") %></p>
    <hr>

    <p>
      <%= link_to '戻る', params[:return_to] || posts_path, class: 'btn btn-secondary mx-4' %>
      <% if admin_signed_in? %>
        <%= link_to '削除', admin_post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger mx-4" %>
      <% elsif current_user == post.user %>
        <%= link_to '編集', edit_post_path(post), class: "btn btn-success mx-4" %>
        <%= link_to '削除', post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger mx-4" %>
      <% end %>
    </p>
  </div>
</div>

app/views/user/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/user/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/user/posts/inactive_index.html.erb
<div class="container posts1">
  <div class="row">
    <div class="col-md-12 my-3">
      <h2 class="text-center">投稿一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <% if @inactive_posts.any? %>
        <%= render 'list', posts: @inactive_posts, url: inactive_posts_path %>
      <% else %>
        <div class="alert alert-info my-4 mx-auto" role="alert">
          <p>まだ投稿がありません。</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center my-2">
      <%= link_to '戻る', my_page_path, class: "btn btn-secondary" %>
    </div>
  </div>

</div>

app/views/user/posts/index.html.erb
<div class="container">
  <div class="row posts1">
    <div class="col-md-12 my-3">
      <h2 class="text-center">投稿一覧</h2>
    </div>
    <% if @posts.where(is_active: true).any? %>
      <%= render 'list', posts: @posts, url: posts_path %>
    <% else %>
      <div class="alert alert-info text-center my-4 mx-auto" role="alert">
        <p>まだ投稿がありません。</p>
      </div>
    <% end %>
  </div>
</div>

app/views/user/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/user/posts/show.html.erb
<div class="container posts1">
  <%= render 'post_detail', post: @post %>
  <div id="comment_index">
    <%= render 'user/comments/index', post: @post, comment: @comment, comments: @comments %>
  </div>
  <!--非同期通信のため、id割振-->
  <%= render 'user/comments/new', post: @post, comment: @comment %>
</div>

app/views/user/posts/tag.html.erb
<div class="container">
  <div class="row posts1">
    <div class="col-md-12 my-3">
      <h2 class="text-center">投稿一覧</h2>
    </div>
    <% if @posts_only_tag.any? %>
      <%= render 'list', posts: @posts_only_tag, url: tag_posts_path %>
    <% else %>
      <div class="alert alert-info text-center my-4 mx-auto" role="alert">
        <p>まだ投稿がありません。</p>
      </div>
    <% end %>
  </div>
</div>

app/views/user/posts/tag_index.html.erb
<%= render 'admin/tags/list', tags: @tags %>